# Banking Customer Churn & Retention Analytics System

## Objective
The goal of this project is to analyze customer churn behavior in a banking system using Python, PostgreSQL, SQL, and Power BI.

This notebook focuses on:
- data understanding
- data quality assessment
- data cleaning
- feature engineering

## Tech Stack
- Python
- Pandas
- NumPy
- PostgreSQL
- Power BI

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/Bank_Churn.csv")

In [3]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerId       10000 non-null  int64
 1   Surname          10000 non-null  str
 2   CreditScore      10000 non-null  int64
 3   Geography        10000 non-null  str
 4   Gender           10000 non-null  str
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(8), str(3)
memory usage: 1015.8 KB

In [5]:
df.describe()

,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [6]:
df.shape

(10000, 13)

In [7]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='str')

In [8]:
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [10]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [11]:
df.columns

Index(['customerid', 'surname', 'creditscore', 'geography', 'gender', 'age',
       'tenure', 'balance', 'numofproducts', 'hascrcard', 'isactivemember',
       'estimatedsalary', 'exited'],
      dtype='str')

In [12]:
df.rename(columns={
    'customerid': 'customer_id',
    'creditscore': 'credit_score',
    'numofproducts': 'num_of_products',
    'isactivemember': 'is_active_member',
    'estimatedsalary': 'estimated_salary',
    'rownumber': 'row_number'
}, inplace=True)

In [13]:
df.columns

Index(['customer_id', 'surname', 'credit_score', 'geography', 'gender', 'age',
       'tenure', 'balance', 'num_of_products', 'hascrcard', 'is_active_member',
       'estimated_salary', 'exited'],
      dtype='str')

In [14]:
df.head()

,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,hascrcard,is_active_member,estimated_salary,exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
df.shape

(10000, 13)

# Data Cleaning Summary

### Cleaning Actions Performed

- Standardized column naming conventions
- Removed unnecessary columns
- Improved dataset readability
- Prepared dataset structure for SQL and Power BI analysis
- Verified data quality and structure consistency

## Feature Engineering 

Creating customer age segments and other Columns to Make visualization better and get better insights to analyze churn behavior across different age demographics.

In [16]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[18, 30, 40, 50, 60, 100],
    labels=['18-30', '31-40', '41-50', '51-60', '60+']
)

In [17]:
df[['age', 'age_group']].head()

   age age_group
0   42     41-50
1   41     41-50
2   42     41-50
3   39     31-40
4   43     41-50

In [18]:
df['salary_band'] = pd.qcut(
    df['estimated_salary'],
    q=4,
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [19]:
df[['estimated_salary', 'salary_band']].head()

   estimated_salary salary_band
0         101348.88        High
1         112542.58        High
2         113931.57        High
3          93826.63      Medium
4          79084.10      Medium

In [20]:
df['balance_group'] = pd.cut(
    df['balance'],
    bins=[-1, 50000, 100000, 150000, 300000],
    labels=['Low', 'Medium', 'High', 'Very High']
)

In [21]:
df[['balance', 'balance_group']].head()

     balance balance_group
0       0.00           Low
1   83807.86        Medium
2  159660.80     Very High
3       0.00           Low
4  125510.82          High

In [22]:
df['churn_status'] = df['exited'].map({
    0: 'Retained',
    1: 'Churned'
})

In [23]:
df['activity_status'] = df['is_active_member'].map({
    0: 'Inactive',
    1: 'Active'
})

In [24]:
df.head()

,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,hascrcard,is_active_member,estimated_salary,exited,age_group,salary_band,balance_group,churn_status,activity_status
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,41-50,High,Low,Churned,Active
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,41-50,High,Medium,Retained,Active
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,41-50,High,Very High,Churned,Inactive
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,31-40,Medium,Low,Retained,Inactive
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,41-50,Medium,High,Retained,Active

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10000 non-null  int64
 1   surname           10000 non-null  str
 2   credit_score      10000 non-null  int64
 3   geography         10000 non-null  str
 4   gender            10000 non-null  str
 5   age               10000 non-null  int64
 6   tenure            10000 non-null  int64
 7   balance           10000 non-null  float64
 8   num_of_products   10000 non-null  int64
 9   hascrcard         10000 non-null  int64
 10  is_active_member  10000 non-null  int64
 11  estimated_salary  10000 non-null  float64
 12  exited            10000 non-null  int64
 13  age_group         9978 non-null   category
 14  salary_band       10000 non-null  category
 15  balance_group     10000 non-null  category
 16  churn_status      10000 non-null  str
 17  activity_status   10000 non-null  str
dtypes: category(3), float64(2), int64(8), str(5)
memory usage: 1.2 MB

In [26]:
df.columns

Index(['customer_id', 'surname', 'credit_score', 'geography', 'gender', 'age',
       'tenure', 'balance', 'num_of_products', 'hascrcard', 'is_active_member',
       'estimated_salary', 'exited', 'age_group', 'salary_band',
       'balance_group', 'churn_status', 'activity_status'],
      dtype='str')

In [27]:
df.to_csv("../data/processed/bank_churn_cleaned.csv", index=False)